### DISCUSSION TITLE
Sending Monitoring change with Home Assistant

### DISCUSSION THREAD

**Discussion by applesoff** [owntracks/android#1991] [Ideas & New Features]
I see it is possible to send monitoring changes with automation apps such as tasker from https://owntracks.org/booklet/features/android
Home assistant has a [broadcast intent feature](https://companion.home-assistant.io/docs/notifications/notification-commands#broadcast-intent). I am having a hard time figuring out how to format the yaml to make this trigger. Could anyone assist me?

**Comment by applesoff** [comment]
I have this so far, but triggering it does not change the mode

```
alias: Update Owntracks
description: ""
triggers:
  - device_id: bb5a31b99644cf3445ba397d42318785
    domain: device_tracker
    entity_id: e8c9c093a20f5bc2c01ec02e39e1d985
    type: enters
    trigger: device
    zone: zone.home
conditions: []
actions:
  - action: notify.mobile_app_s21
    metadata: {}
    data:
      message: command_broadcast_intent
      target: Service
      data:
        intent_package_name: org.owntracks.android
        intent_action: org.owntracks.android.CHANGE_MONITORING
        intent_extras: monitoring:0
mode: single
```
