### DISCUSSION TITLE
Use Home Assistant to send intent to owntracks

### DISCUSSION THREAD

**Discussion by applesoff** [owntracks/android#2096] [Q&A]
I have come up with this script in HA to change monitoring modes in owntracks, but I cannot figure out why it does not function. Am i missing something? 
```
alias: Update Owntracks
description: ""
triggers:
  - device_id: bb5a31b99644cf3445ba397d42318785
    domain: device_tracker
    entity_id: e8c9c093a20f5bc2c01ec02e39e1d985
    type: enters
    trigger: device
    zone: zone.home
conditions: []
actions:
  - service: notify.mobile_app_s21
    data:
      message: "command_broadcast_intent"
      data:
        intent_package_name: "org.owntracks.android"
        intent_action: "org.owntracks.android.CHANGE_MONITORING"
        intent_extras: "monitoring:0"
        ttl: 0
        priority: high
      target: service
```

**Comment by zutewas** [comment]
I know it's not your question, but I can't use your way with service notify in my environment. I'm using a script in HA to set the monitoring modes. For this you you must activate "remote commands" and "remote configuration" in owntracks app.

After this you can publish mqtt messages like this to set the monitoring mode.

```
data:
  qos: "0"
  topic: owntracks/myname/phone/cmd
  payload: >-
    {"_type": "cmd", "action": "setConfiguration", "configuration":{"_type":
    "configuration","monitoring": 0}}
action: mqtt.publish
```

I'm using this script e.g. in automations like:
- if phone not in wlan, set mode 1 (significant)
 - if phone in wlan, set mode 0 (manual)
 -  ...

**Comment by SuperPino64** [comment]
Same problem, why does this not work via HTTP?
```
action: notify.mobile_app_william_a35
data:
  message: command_broadcast_intent
  data:
    intent_package_name: "org.owntracks.android"
    intent_action: "org.owntracks.android.CHANGE_MONITORING"
    intent_extras: "monitoring:1"
    ttl: 0
    priority: high
  target: service
```
In the log (debug) I don´t see anything.
HA companion app reports the notification correct in notification history.
