### ISSUE TITLE
confusing preference setting for TLS

### ISSUE THREAD

**Issue by mnlhfr** [owntracks/android#1268]
hello team,

i just wanted to point out something that confused me while setting up owntracks.

Enabling TLS in the app seems to refer to TLS client certificates and not just a regular TLS connection.

my setup looks like this:
# android app
* preferences -> connection: MQTT
* preferences -> connection -> host: myhost.tld
* preferences -> connection -> port: 443
* preferences -> connection -> identification: user and password i set up in `mosquitto.password`
* preferences -> connection -> security: TLS == DISABLED
# mosquitto-eclipse docker deployment
## mosquitto.conf
```
log_type all
log_facility 5

allow_anonymous false
password_file /mosquitto/config/mosquitto.password

listener 80 
protocol websockets

```
## docker-compose
```
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: otr_mqtt
    labels:
      traefik.enable: true
      traefik.network: traefik
      traefik.http.routers.otr_mqtt_websocket.rule: Host(`myhost.tld`)
      traefik.http.routers.otr_mqtt_websocket.entrypoints: websecure
      traefik.http.services.otr_mqtt.loadbalancer.server.port: 80
    volumes:
      - ./config:/mosquitto/config/
    networks:
      - traefik
```
so my traefik deployment takes care of TLS on the `websecure` endpoint and enabling the "preferences -> connection -> security: TLS " property in the android app will lead to errors which is a little bit confusing since my MQTT deployment isn't even available without TLS.

I am therefor assuming that this setting just refers to the use of client certificates?

Would it make sense to rename "TLS" in the security settings of the app to "Client Certificates" since the app seems to able to distinguish between HTTP and HTTPS connections without any explicit configuration?
