### ISSUE TITLE
Friends face icons disappear if I exit android app and reopen it

### ISSUE THREAD

**Issue by ippocratis** [owntracks/android#1448]
I can't make friends icons appear

Steps:

Resided jpg images to 192x192

`image2card.sh image.jpg username > mosquitto/config/user.json`

Then

`docker exec -it mosquitto mosquitto_pub  -d -h mqtt.example.org -p 8883 --cafile /mosquitto/config/ca.crt --cert /mosquitto/config/server.crt --key /mosquitto/config/server.key -t owntracks/username/device_id/info -f user.json -r`

Restart containers (not even sure this is needed)

The icons appear in the recorder table index http://localhost:8083/table/index.html but not in the android app map,  nor the friends tab nor the recorder live map http://localhost:8083/last/index.HTML (well I think it was not meant to show up there anyway)

**Comment by growse** [comment]
This should work.

Can you double check with `mosquitto_sub` that you're getting the message contents you expect on the topic you expect, and also check the android log to see if it's receiving the message?

**Comment by ippocratis** [comment]
My bad
There was already another user.neon in mosquitto/config as I was trying mosquitto_sub on 1883 earlier

Deleted it and recreated it and everything works fine
thanks
Closing

**Comment by jpmens** [comment]
restarting containers is not necessary.

You've used the retain flag (-r) which is right. The only thing occurring to me is an additional QoS=2 (-q 2), but that shouldn't be the problem ...

**Comment by growse** [comment]
Can you include the relevant section from the android debug log? There should be a message there when it receives an info card.

**Comment by ippocratis** [comment]
Looks like info cards are not received? 
I see topics and locations receiving no cards

**Comment by ippocratis** [comment]
Removed the coresponding topics from mosquitto
Thats kinda safe to do as track history is preserved in recorder store
Also removed cards and photos dog's in recorder store
recreated cards

That seem to work for now

Lets see how it goes

**Comment by ippocratis** [comment]
The face icon disappear if I exit android app and reopen it

**Comment by ippocratis** [comment]
The face icon disappear if I exit android app and reopen it

**Comment by growse** [comment]
> The face icons disappear if I exit android app and reopen it

That smells a little bit like the card is not being published to the MQTT broker with the retain flag. Can you check that if you `mosquitto_sub` to your broker, you get the card messages on an `/info` topic immediately?

**Comment by ippocratis** [comment]
I think I figured this out (fingers crossed)
It turned out I did not had a persistent mosquitto db

The mosquitto/config/mosquitto.conf file was set

```
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data
```

The user was set for the mosquitto service in the docker-compose.yml

```
mosquitto:
        image: eclipse-mosquitto:openssl
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883"
            - "8883:8883"
        volumes:
            - "./mosquitto/config:/mosquitto/config"
            - ./mosquitto/data:/mosquitto/data:rw
            - "./mosquitto/config/passwd:/mosquitto/passwd"
        environment:
            - TZ=Europe/Athens
        user: "1000:1000"
```

But mosquitto/data was not populated

I had to change the permissions to 777 for mosquitto/data
